### ISSUE TITLE
Border-radius broken in single root item menu bar (Lumo theme)

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-menu-bar#98]
![image](https://user-images.githubusercontent.com/4611559/70053739-bca3dd00-15de-11ea-8ab1-a75905dff128.png)

Left-side border-radii are 0.

Affects all browsers.

**Comment by web-padawan** [comment]
It seems like this would be easy to fix by changing this line

https://github.com/vaadin/vaadin-menu-bar/blob/1e31c5f540d60e933499a897dc8288408c253a76/theme/lumo/vaadin-menu-bar-button-styles.html#L67

to 
```css
:host(:first-of-type:not(:nth-last-of-type(2)))
```

Please note that this selector would not work with ShadyCSS because of the [limitation](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs#shadycss-hostzotnotbarnth-child2-doesnt-work-).

**Comment by dasfuu** [comment]
This comes up regularly for us as we have dynamic MenuBar entries depending on application settings and user. We would be very happy if this bug gets fixed anytime soon.

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/web-components/issues/278
